# Generated by Django 5.0.7 on 2024-07-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("set", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="set",
            name="description",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
