# Generated by Django 4.1.13 on 2024-11-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("set", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="set",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
