# Generated by Django 5.0.7 on 2024-07-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("set", "0002_alter_set_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="set",
            name="picture",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
