# Generated by Django 4.1.13 on 2024-11-22 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("set", "0002_set_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="set",
            name="creator",
            field=models.ForeignKey(
                default="66d5af4c39d7d74f5be72f30",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
