version: "3"

volumes:
  node_modules:
  node_modules-3:
services:
  server:
    container_name: studyapp-server
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    command: "python manage.py runserver 0.0.0.0:3003"
    env_file:
      - server/.env
    volumes:
      - ./server:/app
    ports:
      - "3003:3003"
  # front-web:
  #   container_name: abocados-web
  #   restart: always
  #   build:
  #     context: ./front-web
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./front-web:/app
  #     - node_modules:/app/node_modules
  #   env_file:
  #     - front-web/.env
  # front-end:
  #   container_name: abocados-front-end
  #   restart: always
  #   build:
  #     context: ./front-end
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - "3001:3001"
  #   volumes:
  #     - ./front-end:/app
  #     - node_modules-3:/app/node_modules
  #   env_file:
  #     - front-end/.env
