# Generated by Django 4.1.13 on 2025-06-13 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stats",
            name="term",
        ),
    ]
