# Generated by Django 4.1.13 on 2025-06-13 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("term", "0006_termsegment"),
        ("stats", "0002_remove_stats_term"),
    ]

    operations = [
        migrations.AddField(
            model_name="stats",
            name="term",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="term.term"
            ),
            preserve_default=False,
        ),
    ]
