# Generated by Django 5.0.7 on 2024-07-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Term",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("front", models.CharField(max_length=50)),
                ("back", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=100)),
            ],
        ),
    ]
