# Generated by Django 4.1.13 on 2024-10-31 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("term", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="term",
            name="back_alternatives",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
