# Generated by Django 5.0.7 on 2024-07-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("term", "0002_alter_term_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="term",
            name="progress",
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
