# Generated by Django 4.1.13 on 2024-11-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("term", "0002_term_back_alternatives"),
    ]

    operations = [
        migrations.AddField(
            model_name="term",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
