# Generated by Django 4.1.13 on 2025-06-13 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("term", "0005_alter_term_creator"),
    ]

    operations = [
        migrations.CreateModel(
            name="TermSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=10)),
                ("reading", models.CharField(max_length=10)),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="term.term",
                    ),
                ),
            ],
        ),
    ]
